### ISSUE TITLE
Invalid TypeScript declaration files in 4.13.0 release

### ISSUE THREAD

**Issue by Sekhmet** [0xs34n/starknet.js#411]
Starting with 4.13.0 release `dist` contains only bundled `index.js` and `index.d.ts` instead of whole directory tree from previous versions.

This generated `index.d.ts` isn't valid (with `typescript` 4.7.3 and 4.9.3).

```
node_modules/starknet/dist/index.d.ts:1124:41 - error TS2708: Cannot use namespace 'Sequencer' as a value.

1124 declare const index$1_Sequencer: typeof Sequencer;
                                             ~~~~~~~~~

node_modules/starknet/dist/index.d.ts:1125:35 - error TS2708: Cannot use namespace 'RPC' as a value.

1125 declare const index$1_RPC: typeof RPC;
                                       ~~~
 ```
 
 To reproduce, try building TS project that uses `starknet@4.13.0` for example [this](https://github.com/snapshot-labs/checkpoint/compare/sekhmet/starknet-upgrade?expand=1).
 
 This change in `.d.ts` file fixes it, but I'm not sure why broken file was produced:
 ```diff
1124,1125d1123
< declare const index$1_Sequencer: typeof Sequencer;
< declare const index$1_RPC: typeof RPC;
1137,1138c1135,1136
<     index$1_Sequencer as Sequencer,
<     index$1_RPC as RPC,
---
>     Sequencer,
>     RPC,
```

**Comment by ivpavici** [comment]
Thanks! cc: @penovicp

**Comment by penovicp** [comment]
Looks like it's down to how `rollup-plugin-dts` does the bundling for nested namespaces. I'll see if it can be avoided and if not add a script to adjust the `.d.ts` with the changes that @Sekhmet identified.

**Comment by ivpavici** [comment]
@Sekhmet please check with the new release https://github.com/0xs34n/starknet.js/releases/tag/v4.13.1

**Comment by Sekhmet** [comment]
@ivpavici it works with `4.13.1`, thanks!
